[package]
name = "next-visitor-cjs-finder"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
swc_core = { workspace = true }